use_frameworks!

target 'GWHomeKit_Example' do
  pod 'GWHomeKit', :path => '../'

  target 'GWHomeKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
